# Generated by Django 2.2.6 on 2019-11-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/carousel')),
                ('heading', models.CharField(blank=True, max_length=150)),
                ('paragraph', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
