# Generated by Django 2.2.6 on 2019-11-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexcarousel',
            name='first',
            field=models.BooleanField(default=False),
        ),
    ]
