# Generated by Django 2.2.6 on 2019-11-17 16:34

from django.db import migrations
import exclusivebooleanfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_indexcarousel_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexcarousel',
            name='the_one',
            field=exclusivebooleanfield.fields.ExclusiveBooleanField(default=False),
        ),
    ]
