# Generated by Django 2.2.6 on 2019-11-18 12:10

from django.db import migrations
import exclusivebooleanfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_indexcarousel_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexcarousel',
            name='first',
            field=exclusivebooleanfield.fields.ExclusiveBooleanField(),
        ),
    ]
