# Generated by Django 2.2.6 on 2019-11-17 16:49

from django.db import migrations
import exclusivebooleanfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_indexcarousel_the_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexcarousel',
            name='the_one',
        ),
        migrations.AlterField(
            model_name='indexcarousel',
            name='first',
            field=exclusivebooleanfield.fields.ExclusiveBooleanField(default=True),
        ),
    ]
