# Generated by Django 2.2.6 on 2019-11-17 16:59

from django.db import migrations
import exclusivebooleanfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20191117_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexcarousel',
            name='first',
            field=exclusivebooleanfield.fields.ExclusiveBooleanField(),
        ),
    ]
