# Generated by Django 3.0 on 2019-12-06 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='active1',
        ),
    ]
