# Generated by Django 3.0 on 2019-12-17 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=250)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='GBP Total Order')),
                ('email_address', models.EmailField(blank=True, max_length=250, verbose_name='Email Address')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('billing_name', models.CharField(blank=True, max_length=250)),
                ('billing_address1', models.CharField(blank=True, max_length=250)),
                ('billing_city', models.CharField(blank=True, max_length=250)),
                ('billing_postcode', models.CharField(blank=True, max_length=10)),
                ('billing_country', models.CharField(blank=True, max_length=200)),
                ('shipping_name', models.CharField(blank=True, max_length=250)),
                ('shipping_address1', models.CharField(blank=True, max_length=250)),
                ('shipping_city', models.CharField(blank=True, max_length=250)),
                ('shipping_postcode', models.CharField(blank=True, max_length=10)),
                ('shipping_country', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='GBP Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
    ]
