# Generated by Django 2.2.6 on 2019-11-03 20:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('size', models.CharField(blank=True, max_length=5)),
                ('stock', models.IntegerField()),
                ('photo_main', models.ImageField(upload_to='photos')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos')),
                ('is_for_sale', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('type_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.ProductType')),
            ],
        ),
    ]
