# Generated by Django 2.2.6 on 2019-11-04 15:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191103_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buys',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.DO_NOTHING, to='products.SizeChart'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
