# Generated by Django 2.2.6 on 2019-11-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191104_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='character',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='series',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, max_length=180),
        ),
    ]
