# Generated by Django 3.0 on 2019-12-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191206_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbrand',
            old_name='brands',
            new_name='brand_name',
        ),
    ]
