# Generated by Django 3.0 on 2019-12-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191206_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_sizes',
            field=models.BooleanField(default=False),
        ),
    ]
