# Generated by Django 2.2.6 on 2019-11-16 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20191116_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.SizeChart'),
        ),
    ]
