# Generated by Django 3.0 on 2019-12-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_stock_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_sizes',
        ),
    ]
