# Generated by Django 3.0 on 2019-12-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_stock_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='apply_sizes',
            field=models.BooleanField(default=False),
        ),
    ]
