# Generated by Django 3.0 on 2019-12-17 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_apply_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='apply_sizes',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='GBP Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_l',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Stock Size L'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_m',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Stock Size M'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_s',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Stock Size S'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_xl',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Stock Size XL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_xs',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Stock Size XS'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_xxl',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Stock Size XXL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_xxxl',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Stock Size XXXL'),
        ),
    ]
