# Generated by Django 3.0 on 2020-01-04 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191205_2157'),
        ('products', '0009_auto_20191217_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carousel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.IndexCarousel'),
        ),
    ]
