# Generated by Django 2.2.6 on 2019-11-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20191116_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type_code',
            new_name='product_type',
        ),
    ]
