# Generated by Django 2.2.6 on 2019-11-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20191116_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbrand',
            old_name='product_brand',
            new_name='brands',
        ),
        migrations.RenameField(
            model_name='producttype',
            old_name='product_type',
            new_name='types',
        ),
    ]
