# Generated by Django 2.2.6 on 2019-11-18 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20191117_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_s',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
