# Generated by Django 2.2.6 on 2019-11-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_stock_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_all',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
