# Generated by Django 2.2.6 on 2019-11-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_stock_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_all',
            field=models.PositiveIntegerField(),
        ),
    ]
