# Generated by Django 2.2.6 on 2019-11-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20191118_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_all',
        ),
    ]
