# Generated by Django 2.2.6 on 2019-11-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20191118_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock_l',
            new_name='l',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock_m',
            new_name='m',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock_s',
            new_name='s',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock_xl',
            new_name='xl',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock_xs',
            new_name='xs',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock_xxl',
            new_name='xxl',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock_xxxl',
            new_name='xxxl',
        ),
    ]
