# Generated by Django 2.2.6 on 2019-11-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20191118_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='l',
            new_name='stock_l',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='m',
            new_name='stock_m',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='s',
            new_name='stock_s',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='xl',
            new_name='stock_xl',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='xs',
            new_name='stock_xs',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='xxl',
            new_name='stock_xxl',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='xxxl',
            new_name='stock_xxxl',
        ),
    ]
