# Generated by Django 2.2.6 on 2019-11-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20191118_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='is_in_navbar_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='is_in_navbar_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
